--SELECT KOMUTU

SELECT 
KOLON1,KOLON2,KOLON3,...
FROM TABLOADI
WHERE <ŞARTLAR>

--INSERT KOMUTU

INSERT INTO TABLOADI
(KOLON1,KOLON2,KOLON3,...)
VALUES
(DEĞER1,DEĞER2,DEĞER3,...)

--UPDATE KOMUTU

UPDATE TABLOADI SET
KOLON1 = DEĞER1 , KOLON2 = DEĞER2 , KOLON3 = DEĞER3,...
WHERE <ŞARTLAR>


--DELETE KOMUTU

DELETE FROM TABLO
WHERE <ŞARTLAR>


--TRUNCATE KOMUTU

TRUNCATE TABLE TABLOADI


--WHERE KOMUTU

SELECT
KOLON1,KOLON2,KOLON3,...
FROM TABLOADI
WHERE <ŞARTLAR>

--Örneğin tablodaki verilerden müşteri ismi Ayşe olanları getirmek istiyoruz ;

SELECT * FROM CUSTOMERS 
WHERE CUSTOMERNAME = 'AYŞE'

--ÖRNEKLER

SELECT * FROM CUSTOMERS
WHERE CITY = 'İSTANBUL'
 
-- = :EŞİTTİR.

SELECT * FROM CUSTOMERS
WHERE CITY <> 'İSTANBUL'

-- < > :EŞİT DEĞİLDİR.

SELECT * FROM CUSTOMERS
WHERE BIRTHDATE >'1980-01-01'

-- > :BÜYÜKTÜR.

SELECT * FROM CUSTOMERS
WHERE CUSTOMERID<1

-- < :KÜÇÜKTÜR.

SELECT * FROM CUSTOMERS WHERE CUSTOMERID>=1

-- >= :BÜYÜKTÜR YA DA EŞİTTİR.

SELECT * FROM CUSTOMERS WHERE CUSTOMERID<=1

-- <= :KÜÇÜKTÜR YA DA EŞİTTİR.

SELECT * FROM CUSTOMERS 
WHERE BIRTHDATE BETWEEN '1980-01-01' AND '1990-12-31'

-- BETWEEN :ARASINDADIR.

SELECT * FROM CUSTOMERS 
WHERE NAMESURNAME LIKE '%AYSE%'

-- LIKE :İLE BAŞLAR,İLE BİTER,İÇERİR.

SELECT * FROM CUSTOMERS 
WHERE CITY IN ('ANKARA','İSTANBUL','İZMİR')

-- IN :İÇİNDEDİR.

SELECT * FROM CUSTOMERS 
WHERE NAMESURNAME NOT LIKE '%AYSE%'

-- NOT LIKE :İLE BAŞLAMAZ,İLE BİTEMEZ,İÇERMEZ.

SELECT * FROM CUSTOMERS 
WHERE CITY NOT IN ('ANKARA','İSTANBUL','İZMİR')

-- NOT IN :İÇİNDE DEĞİLDİR.


--İsmi Ayse ile başlayanları getir dersek;

SELECT * FROM CUSTOMERS 
WHERE CUSTOMERNAME = 'AYSE%'

--İsminin içinde Ayse geçenleri getir dersek;

SELECT * FROM CUSTOMERS 
WHERE CUSTOMERNAME = '%AYSE%'

--İsmi Ayse ile bitenleri getir dersek;

SELECT * FROM CUSTOMERS 
WHERE CUSTOMERNAME = '%AYSE'

--2.ismi Ali olanları getir dersek;

SELECT * FROM CUSTOMERS
WHERE NAMESURNAME LIKE '% ALİ %'


--AND : VE

--OR : VEYA

SELECT * FROM CUSTOMERS 
WHERE CITY = 'İSTANBUL' AND DISTRICT='ÜSKÜDAR' 
OR DISTRICT='SARIYER'


--DISTINCT KOMUTU : Verileri filtrelemek için kullanılır.Tekrar eden verileri tekilleştirir.

SELECT DISTINCT
KOLON1,KOLON2,KOLON3,..
FROM TABLOADI
WHERE <ŞARTLAR>

SELECT DISTINCT CITY FROM CUSTOMERS --Aynı şehir birden fazla kez yazılmışsa sadece bir tane yazdırır.

--ORDER BY KOMUTU :Verileri sıralamak için kullanılır.

SELECT
KOLON1,KOLON2,KOLON3,..
FROM TABLOADI
WHERE <ŞARTLAR>
ORDER BY KOLON1 ASC,KOLON2 DESC,..

--ASC : A-Z Küçükten büyüğe göre sıralar. (Varsayılan olarak kullanılır.)
--DESC : Z-A Büyükten küçüğe göre sıralar.

--TOP KOMUTU :Verileri belli bir sayıda sıralamak için kullanılır. TOP komutu ile veritabanındaki tablolardaki kayıtları sıralayabiliriz.

SELECT TOP N
KOLON1,KOLON2,KOLON3,..
FROM TABLOADI
WHERE <ŞARTLAR>
ORDER BY KOLON1 ASC,KOLON2 DESC,..

--DDL KOMUTLARI (DATA DEFINITION LANGUAGE)

--CREATE KOMUTU

CREATE TABLE <TABLENAME>
(KOLON1 TİP1,KOLON2 TİP2.KOLON3 TİP3,...)


--ALTER KOMUTU

ALTER TABLE <TABLENAME>
ADD COLUMN --Tabloya olmayan bir kolon ekler.


ALTER TABLE <TABLENAME>
ALTER COLUMN --Mevcut kolonu değiştirir.


ALTER TABLE <TABLENAME>
DROP COLUMN --Eklediğimiz kolonu siler.


ALTER TABLE <TABLENAME>
ADD CONSTRAINT


ALTER TABLE <TABLENAME>
DROP CONSTRAINT

--DROP KOMUTU 

DROP TABLE <TABLENAME>






















